{{- if .Values.standaloneScheduler }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "mageai.schedulerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mageai.schedulerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mageai.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.redis.enabled .Values.redis.customRedisURL }}
      initContainers:
        - name: wait-for-redis
          image: alpine
          env:
          {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: redis://{{ .Release.Name }}-redis-headless:6379/0
          {{- else if .Values.redis.customRedisURL }}
            - name: REDIS_URL
              value: {{ .Values.redis.customRedisURL }}
          {{- end }}
          command: ["sh", "-c", "until nc -z -v $(echo $REDIS_URL | cut -d'/' -f3 | cut -d':' -f1) $(echo $REDIS_URL | cut -d'/' -f3 | cut -d':' -f2); do sleep 1; done"]
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- if .Values.scheduler.resources }}
              {{- toYaml .Values.scheduler.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ include "mageai.fullname" . }}-env
            {{- end }}
            {{- if or (.Values.existingSecret) (.Values.secrets) }}
            - secretRef:
                name: {{ include "mageai.secretName" . }}
            {{- end }}
          env:
          {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
          {{- else if .Values.extraEnvs }}
            {{- toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.enabled }}
            - name: REDIS_URL
              value: redis://{{ .Release.Name }}-redis-headless:6379/0
          {{- else if .Values.redis.customRedisURL }}
            - name: REDIS_URL
              value: {{ .Values.redis.customRedisURL }}
          {{- end }}
            - name: INSTANCE_TYPE
              value: scheduler
          volumeMounts:
          {{- if .Values.volumes }}
            - name: mage-fs
              mountPath: /home/src
          {{- else if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- else if .Values.extraVolumes -}}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
