{{- if and (not .Values.standaloneScheduler) .Values.pdb.create }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mageai.fullname" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
spec:
   {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.pdb.maxUnavailable ( not .Values.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mageai.selectorLabels" . | nindent 6 }}
...
{{- end }}
